version: 2
jobs:
  build-backend:

    working_directory: ~/Backend
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout



      - restore_cache:
          key: circleci-backend-java-spring-{{ checksum "BackEnd/pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-backend-java-spring-{{ checksum "BackEnd/pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/BackEnd-java-spring-0.0.1-SNAPSHOT.jar
    
  build-frontend: 
    docker:
      - image: circleci/node:12.18.3-browsers
      
    working_directory: ~/FrontEnd

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "FrontEnd/package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache

          key: v1-dependencies-{{ checksum "FrontEnd/package.json" }}

      - run: yarn test

workflows:
  version: 2
  build_frontend_and_backend:
    jobs:
      - build-backend
      - build-frontend
